spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MSProjet?createDatabaseIfNotExist=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: {cipher}fa58f66bec8022a6d075f403f9910a0ac5492e0ca1acac0404a537f312ac2d97
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
microservice:
  utilisateur:
    url: http://localhost:9090
