spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MSUtilisateur?createDatabaseIfNotExist=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: "{cipher}fa58f66bec8022a6d075f403f9910a0ac5492e0ca1acac0404a537f312ac2d97"
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
management:
  endpoints:
    web:
      exposure:
        include: refresh
server:
  port: 8090

eureka:
  client:
    registerWithEureka: true # Facultatif
    fetchRegistry: true # Facultatif
    preferIpAddress: true # Facultatif
    serviceUrl:
      defaultZone: http://localhost:8070/eureka
